game:
  chat:
    # [true | false] Allows spectators to chat in global
    allow-spectator-global: false

    # [type=String] Players must prepend this to speak in global chat
    global-chat-token: "|"

  env:
    worldborder:
      visual:
        # [distance | time | none]
        type: distance
        # [blocks | seconds]
        amount: 20

      chat:
        # [true | false] Whether or not to show when the world border starts/stops shrinking (only if the initial and end sizes aren't equal to each other)
        shrinkStateChange: true
        # [minutes, 0 to disable] Interval of notifying the server how far the world border is away (only if the initial and end sizes aren't equal to each other)
        shrinkInterval: 10

      size:
        # [diameter] Amount of blocks the world border should occupy at the beginning of the match
        initial: 2500
        # [diameter] Amount of blocks the world border should occupy at its latest
        final: 200

        # [minutes] Amount of time before starting to shrink
        shrinkDelay: 30
        # [minutes] Amount of time to spend shrinking
        shrinkDuration: 90

    # [true | false] Set to true if time should stand stil
    eternal-day: false

  sidebar:
    title: Vexian UHC Season 2

    # [minutes, 0 to disable] Episode length
    timer-length: 20

  stats:
    # [health | playerKillCount | none] Stats to show in the tablist or below the players' names
    in-tablist: health
    under-name: none

  team:
    # [true | false] Whether players on the same team can hurt each other
    friendly-fire: true

    # [always | never | own-team | other-teams]
    death-message: always
    nametag: always
    player-collision: always

    # [seconds]
    death-kick: 10

discord:
  # [true | false] Automatically manage roles in Discord
  enable: true

  # The credentials for the 'bot' account
  credentials:
    email:
    password:

  # [type=String] The channel ID of the channel you'd like the bot to post messages in. Needs to be the server you'll be talking in
  channel-id:
