name: VaksUHC
version: 0.2
author: PhotonBurst
main: com.photonburst.VaksUHC.Main

commands:
  vuhc:
    description: Command containing all the things you'd need for regulating a UHC event!
    usage: /vuhc